apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ibnuzamra/frontend-stg:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 600m
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 384Mi
  selector:
    matchLabels:
      app: client
